CREATE TABLE `user` (
	`user_no` INT(11) NOT NULL AUTO_INCREMENT,
	`id` VARCHAR(100) NULL DEFAULT NULL,
	`name` VARCHAR(100) NULL DEFAULT NULL,
	`password` VARCHAR(100) NULL DEFAULT NULL,
	`hobby` VARCHAR(200) NULL DEFAULT NULL,
	PRIMARY KEY (`user_no`),
	UNIQUE INDEX `id` (`id`)
)